### ISSUE TITLE
Mohammad Musa: working with code, Week 1

### ISSUE THREAD

**Issue by Mohammad-Musa** [HackYourFutureBelgium/class-9-10#11]
> !:warning:! Replace `your-user-name` with your actual GitHub user name and `repo-name` with the name of your class repo !:warning:!

- [x] :egg: [Group Intro Repo](https://github.com/Mohammad-Musa/Introduction)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/Mohammad-Musa/class-9-10/blob/master/student-bios/Mohammad-Musa.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/Mohammad-Musa/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://mohammad-musa.github.io/), [Source](https://github.com/Mohammad-Musa/Introduction/blob/master/README.md)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/Mohammad-Musa/projects/1)

**Comment by colevandersWands** [comment]
Two things:
* your home page should be in a repo called /Muhammad-Musa.github.io, then your home page is live at `Muhammad-Musa.github.io`
* the project board assignment has changed since last time around, can you add one here so it's more accessible? https://github.com/Mohammad-Musa?tab=projects

**Comment by Mohammad-Musa** [comment]
@colevandersWands, thank you for the feedback.
I hope it fixed now! :)

**Comment by colevandersWands** [comment]
The profile is good to go!

But this link still doesn't have a project board: https://github.com/Mohammad-Musa?tab=projects

**Comment by Mohammad-Musa** [comment]
Could you check it please, I already fixed it!

**Comment by colevandersWands** [comment]
I still don't see any project boards when I go to this link: https://github.com/Mohammad-Musa?tab=projects
Click on this link and you will see what I mean.

Could you also replace Your Name in the title of the issue with Mohammad Musa?

**Comment by Mohammad-Musa** [comment]
I replaced the name.
I changed this  link https://github.com/Mohammad-Musa?tab=projects change to the new one which is: https://github.com/users/Mohammad-Musa/projects/1
I hope it solved now! :)

**Comment by colevandersWands** [comment]
@HazemBittar ,

**Comment by colevandersWands** [comment]
@Mohammad-Musa , when you think you've made the corrections can you move your card back into "READY FOR REVIEW"?  otherwise we don't know to re-check your work

@HazemBittar , Commenting in your classmates' issues is a great thing (and thank you for taking ownership!), but moving cards between "READY FOR REVIEW", "NEEDS REVISION", and "DONE" is for coaches.

**Comment by colevandersWands** [comment]
@Mohammad-Musa , the link you shared is a 404 https://github.com/users/Mohammad-Musa/projects/1
and I still don't see any project boards when I go here: https://github.com/Mohammad-Musa?tab=projects

**Comment by colevandersWands** [comment]
There still is still no project board on your main user profile, the link from my last comment is still 404.

when i go to the link I shared above there should be something like this: https://github.com/users/LujiAnna/projects/1

**Comment by Mohammad-Musa** [comment]
could you check your slack please, I sent you there!

**Comment by colevandersWands** [comment]
wierd.  #internet
