### ISSUE TITLE
Gelila : Incremental-development, week -1, homework

### ISSUE THREAD

**Issue by gelilaa** [HackYourFutureBelgium/class-9-10#161]
# Week 1

## Module Name

- [assignments](https://github.com/hackyourfuturebelgium/incremental-development/tree/master/week-1)

## Prep Work

- [x] Git
- [x] Agile Development
- [x] Relative vs Absolute path
- [x] Inspecting the DOM
- [x] HTML 5 Semantic Layout

---

## In Class

- [x] Isolate[live](https://gelilaa.github.io/group-branches/), [source](https://github.com/gelilaa/group-branches)
- [x] Integrate: [live](https://gelilaa.github.io/html-branching/), [source](https://github.com/gelilaa/html-branching)

---

### Suggested Study

- [x] Git & Github
- [x] HTML & CSS

### Exercises:

- [x]   🥚  html-css-git-exercises - Week 1: [repo](https://github.com/gelilaa/html-css-git-exercises/tree/master/week-1)
- [x] :hatching_chick: HTML-CSS-Practice-Problems [repo](https://github.com/gelilaa/HTML-CSS-Practice-Problems)
### Project

project name:

- [x] [repo](https://github.com/gelilaa/acme-web-design)
- [x] [live](https://gelilaa.github.io/acme-web-design/)
- [x] [development-strategy](https://github.com/gelilaa/acme-web-design/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] A complete README

**Comment by snicoll** [comment]
@gelilaa good job. I've found a few issues, can you please have a look?

* There are [HTML validation errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fgelilaa.github.io%2Fhtml-branching%2F) for your html branching project (love the emoji, keep them coming!)
* There are [HTML validation errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fgelilaa.github.io%2Facme-web-design%2F) for your `acme-web-design` project
* Rather than describing in the development strategy what you're going to do, focus on what value you add to the service. What is the user going to benefit from?  The step0 describes that so please review that


I can see you've used PRs to merge your branches via GitHub. There is nothing wrong with that but I'd like you to do that locally to make sure you're comfortable with the workflow. Rather than pushing the branch to GitHub and creating a PR for it, try to merge the branch on your machine (using whatever tool you fancy).

**Comment by gelilaa** [comment]
@snicoll thank you for the suggestions.

 I have corrected the issues per your request.
- I have validated my html branching project
- I have also validated my `acme-web-design` project
- I have also wrote a new [development strategy](https://gelilaa.github.io/acme-web-design/development-strategy)
And for my next projects I will try to do my merges from the gitkraken or my terminal.

**Comment by snicoll** [comment]
@gelilaa thanks for the feedback. The two links above still show some HTML validation errors. Have I missed something? Do you need help about those?

Thanks for the update on the development strategy. The title/description should focus on the added value (what do you bring to the site? What feature do you add. See other development strategies for reference. 

Let me know if you have any question.

**Comment by gelilaa** [comment]
Hey @snicoll , I have done the HTML validation errors again

- [here](https://validator.w3.org/nu/?doc=https%3A%2F%2Fgelilaa.github.io%2Fhtml-branching%2F) is the link for the html branching project, showing No errors or warnings.
- [here](https://validator.w3.org/nu/?doc=https%3A%2F%2Fgelilaa.github.io%2Facme-web-design%2F) showing 2 warnings to consider Consider using the h1 element as a top-level heading only. I have already tried to change the html and css per the warnings' suggestions but the result is not flattering for the website.
- For the development strategy, it would help me a lot if you can send me a reference link that I can compare to. 

Thank you

**Comment by snicoll** [comment]
@gelilaa I am afraid my CSS skills have reached their capacity and I can't help you for point 2. Perhaps @colevandersWands can chime in?

I personally like [this development strategy](https://github.com/adekimpianna/acme-web-design/blob/master/development-strategy.md#1-user-story-first-time-knowing-the-company). See the difference in style where you should describe what the added value is rather than what you're actually going to do as a developer.

**Comment by snicoll** [comment]
By the way, I should add you're very close to completion here so keep up the good work!

**Comment by gelilaa** [comment]
@snicoll 
[here](https://validator.w3.org/nu/?doc=https%3A%2F%2Fgelilaa.github.io%2Facme-web-design%2F)is the link for acme-web-design  showing No errors or warnings. I specified the tag and it worked. 
I have updated the  [development strategy](https://gelilaa.github.io/acme-web-design/development-strategy) . 
Hopefully I'm on the right track now. Thank you for the suggestions and encouragements.

**Comment by snicoll** [comment]
All good, thanks for the quick follow-up!
